### ISSUE TITLE
nginx support

### ISSUE THREAD

**Issue by Morgy93** [meanbee/docker-magento#44]
This container looks awesome, but how about some 7.0-nginx ?

**Comment by tgerulaitis** [comment]
I'd love to have one, but since there isn't an official php+nginx image, it would be quite some work to build it. On top of that Nginx doesn't really have mod_php the way Apache does. It's normally configured with passing requests into php-fpm for processing. You can use our existing 7.0-fpm image with an Nginx container to achieve that:

```
web:
  image: nginx:1.9
  volumes:
    - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - php
  ...
php:
  image: meanbee/magento:7.0-fpm
  ports:
    - 9000
  ...
```

In your `nginx.conf` configure the php requests to be passed to php-fpm running at `php:9000`.
