### ISSUE TITLE
Settings for email

### ISSUE THREAD

**Issue by gety9** [meanbee/docker-magento#60]
Guys,

Could you clarify how email work here?

I have ENABLE_SENDMAIL=true

Email jobs are executed [admin](https://puu.sh/zhYvF/a9b091bf94.png), [logs](https://puu.sh/zhYxI/8a25be1e49.png). But no emails are sent.

Do i have to make extra configuration somewhere in docker?

Or 

Do I have to configure local email server for this? Something like [this](https://gist.github.com/raelgc/6031306) or [this](http://inchoo.net/magento/installation-and-configuration-of-local-mail-server-for-windows-hmail-server/)?

p.s. i am on windows if it makes the difference.

**Comment by tgerulaitis** [comment]
Hi @gety9 ,

`ENABLE_SENDMAIL=true` set on the php container (either web of fpm, whichever you use for processing PHP requests) and cron container should be all you need. The PHP docker containers have a mail server installed inside them, disabled by default but enabled if the environment variable is set, so you don't need a separate email server on your host machine.

There could be several reasons for emails not getting through, though:

1. The docker container is failing to send them. You could run `docker-compose exec cron mailq` to check the local email queue.
2. The email domain could be configured to reject emails from unverified addresses. Have you got an SPF record configured for your email domain?
3. Are you sure the emails aren't being marked as spam? Some email clients are overzealous at filtering out emails coming from development/test addresses.

Cheers,
Tomas

**Comment by gety9** [comment]
@tgerulaitis 

Thank you for your reply,

I am sure about 3, will check and report on 1 tomorrow.

But i think 2 might be the reason. For email domain i simply put domain-dev.com, so it's not real domain.
Do i need to put real domain in docker-compose?

**Comment by tgerulaitis** [comment]
@gety9 ,

It doesn't have to be a real domain, just one that doesn't restrict you sending emails. `domain-dev.com` may be a domain that you've made up, but it's still a domain that somebody owns (specifically, it seems some company called Blue Ridge Global) and they are control of who is allowed to send emails from that domain.

If you want to use a fake domain, I recommend using `example.com`. It is a domain that is [reserved](https://en.wikipedia.org/wiki/Example.com) by the IANA for documentation purposes. It has no real website associated for it and no restrictions on it. We've been using `test@example.com` to send email addresses from our dev environments successfully.

Cheers,
Tomas

**Comment by gety9** [comment]
@tgerulaitis 

Still not working, please help me understand what am i doing wrong.

Results of 1:
```
$ docker exec cpd1_web_1 mailq
MSP Queue status...
/var/spool/mqueuTotal requests: 0
MTA Queue status...
/var/spool/mqueuTotal requests: 0
```
```
$ docker exec cpd1_cron_1 mailq
MSP Queue status...
/var/spool/mqueuTotal requests: 0
MTA Queue status...
/var/spool/mqueuTotal requests: 0
```
They are the same before and after test order is placed(time when email is supposed to be firing)
core_email_queue_send_all are fired successfully (shown as green in AOE Scheduler Timeline) every minute. Exactly same set-up emails correctly on live server.

For 2 i've added example.com everywhere, cause i was not sure which particular parameter is responsible for email domain.

Here is my new docker-compose
```
version: "2"
services:
  web:
    image: meanbee/magento:5.6-apache
    hostname: example.com
    ports:
      - "80:80"
    volumes_from:
      - appdata
    environment:
      - VIRTUAL_HOST=example.com
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
      - ENABLE_SENDMAIL=true
    links:
      - db

  cron:
    image: meanbee/magento:5.6-cli
    hostname: cron.example.com
    working_dir: /var/www/html
    command: /run-cron.sh
    volumes_from:
      - appdata
    environment:
      - ENABLE_SENDMAIL=true
    links:
      - db

  cli:
    image: meanbee/magento:5.6-cli
    hostname: cli.example.com
    working_dir: /var/www/html
    command: /bin/true
    volumes_from:
      - appdata
    environment:
      - AWS_ACCESS_KEY_ID=00000000000000000000
      - AWS_SECRET_ACCESS_KEY=0000000000000000000000000000000000000000
      - AWS_REGION=eu-west-1
      - AWS_BUCKET=magedbm
      - AWS_MEDIA_BUCKET=magemm
    links:
      - db

  db:
    image: meanbee/magento-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_DATABASE=pdr_new

  appdata:
    image: tianon/true
    volumes:
      - /e/repos/pdr.com/html:/var/www/html
```

Also i set `test@example.com` in all emails in configuration>general>Store Email Addresses

For 3 checked spam folder, and sent test email from my person email address just to make sure. This email address works.
