### ISSUE TITLE
Modman fails to create symbolic link

### ISSUE THREAD

**Issue by gety9** [meanbee/docker-magento#63]
Guys hi,

Modman fails to create symbolic link. I use this command:
`docker exec -ti t1_cron_1 modman deploy-all`

Getting [this error](https://puu.sh/ApXBk/8901ecd1c2.png):
```
Deploying aoepeople_aoe_templatehints to /var/www/html
ln: failed to create symbolic link '/var/www/html/app/etc/modules/Aoe_TemplateHints.xml': Read-only file system
ERROR: Unable to create symlink (/var/www/html/app/etc/modules/Aoe_TemplateHints.xml):
 app/etc/modules/Aoe_TemplateHints.xml app/etc/modules/Aoe_TemplateHints.xml
ERROR: Error occurred while deploying 'aoepeople_aoe_templatehints'.
```

Details:
I am trying to make post-update-cmd script for composer work and it's giving [the same error](https://puu.sh/ApXCJ/007c7ee48c.png)

Here is the composer.json i use just in case if something is wrong there:
```
{
    "minimum-stability":"dev",
    "require": {
		"aoepeople/composer-installers": "*",
        "firegento/pdf":"*",
        "integer-net/autoshipping":"*",
        "aoepeople/aoe_templatehints":"*"
    },
    "repositories": [
	{ "type": "composer",   "url": "https://packages.firegento.com" }
    ],
    "extra": {
        "installer-paths": {
            "htdocs": ["type:magento-source"],
            ".modman/{$vendor}_{$name}/": ["type:magento-module"]
        }
    },
    "config": {
	"discard-changes": true
    },
    "scripts": {
        "pre-install-cmd": [
            "mkdir -p ./.modman && echo \"htdocs/\" > ./.modman/.basedir"
        ],
        "post-install-cmd": [
            "mv ./htdocs/var ./var",
            "mv ./htdocs/media ./media",
            "ln -rs ./var ./htdocs/var",
            "ln -rs ./media ./htdocs/media"
        ],
        "post-update-cmd": [
            "modman deploy-all --force",
            "n98-magerun cache:flush",
            "n98-magerun index:reindex:all"
        ]
    }
}
```

There were issues with symbolic links on Windows but seems like they were fixed:
https://forums.docker.com/t/symlinks-on-shared-volumes-not-supported/9288/42

**Comment by tgerulaitis** [comment]
@gety9 , What platform and Docker version are you running? Could you post your `docker-compose.yml` file?

This shouldn't be related to anything specific to the image as the image simply runs `modman` (no additional magic) and looks like modman is trying to put the symlink in the correct place. So I'm thinking the most likely issue here is one of:

1. `/var/www/html` is mounted as read-only in `docker-compose.yml`
2. There actually is no more available space in `/var/www/html`
3. Mount permissions issues - the directory is owned by another user and due to the restrictions on `root` user in Docker on some platforms,`root` can't write to it.

**Comment by gety9** [comment]
@tgerulaitis, 

I am using Docker toolbox on Windows 10 home
```
Client:
 Version:       18.01.0-ce
 API version:   1.26 (downgraded from 1.35)
 Go version:    go1.9.2
 Git commit:    03596f51b1
 Built: Thu Jan 11 22:29:41 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      1.13.1
  API version:  1.26 (minimum version 1.12)
  Go version:   go1.7.5
  Git commit:   092cba3
  Built:        Wed Feb  8 08:47:51 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

According to [this suggestion](https://github.com/docker/toolbox/issues/619#issuecomment-282591417) tried running it as administrator - no luck.

I am using similar docker-compose.yml as suggested - just added phpadmin and adjusted ports, here it is:
```
version: "2"
services:
  web:
    image: meanbee/magento:5.6-apache
    hostname: magento-dev.docker
    ports:
      - "81:80"
    volumes_from:
      - appdata
    environment:
      - VIRTUAL_HOST=magento-dev.docker
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
      - ENABLE_SENDMAIL=true
    links:
      - db

  cron:
    image: meanbee/magento:5.6-cli
    hostname: cron.magento-dev.docker
    working_dir: /var/www/html
    command: /run-cron.sh
    volumes_from:
      - appdata
    environment:
      - ENABLE_SENDMAIL=true
    links:
      - db

  cli:
    image: meanbee/magento:5.6-cli
    hostname: cli.magento-dev.docker
    working_dir: /var/www/html
    command: /bin/true
    volumes_from:
      - appdata
    environment:
      - AWS_ACCESS_KEY_ID=00000000000000000000
      - AWS_SECRET_ACCESS_KEY=0000000000000000000000000000000000000000
      - AWS_REGION=eu-west-1
      - AWS_BUCKET=magedbm
      - AWS_MEDIA_BUCKET=magemm
    links:
      - db

  admin:
    image: nazarpc/phpmyadmin
    ports:
      - "1235:80"
    links:
      - db:mysql  
      
  db:
    image: meanbee/magento-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_DATABASE=centralp_newpark

  appdata:
    image: tianon/true
    volumes:
      - /e/repos/t.com/html:/var/www/html

```
