### ISSUE TITLE
Xdebug configuration

### ISSUE THREAD

**Issue by gety9** [meanbee/docker-magento#75]
Is anything else should be done besides putting XDEBUG_CONFIG="remote_connect_back=1 remote_enable=1 idekey={IDEKEY}" in environmental variables ?

For some reason phpstorm and xdebug do not see each other.

Steps we did:
1 Added environmental variable

```
services:
  web:
    image: meanbee/magento:5.6-apache
    hostname: magento-dev.docker
    ports:
      - "80:80"
    volumes_from:
      - appdata
    environment:
      - VIRTUAL_HOST=magento-dev.docker
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
      - ENABLE_SENDMAIL=true
      - XDEBUG_CONFIG="remote_connect_back=1 remote_enable=1 idekey=phpstorm"
    links:
      - db
```

2 In phpstorm created php remote debug server with out host name and port 9000

3 Enabled cookie 

Is there anything else that should be done?
